### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by cod1239** [jingweilin/YGTQ#1]
首先恭喜你的好名次
不过注意到，github是一个开放空间，任何人都可以浏览你的项目，特别是在关键词比较明显的情况下，不知这是否是你的本意？
另外你太厉害啦！求加微信交流经验~~微信号finnzsp

**Comment by jingweilin** [comment]
感谢提醒，因为另一名队友没有gitlab的账号才使用了这个，赛后是准备公开项目的，现在还是先把关键词改掉了。比赛完有机会交流！
